### ISSUE TITLE
Cannot start: TypeError: Cannot read property 'passport' of undefined

### ISSUE THREAD

**Issue by DarthHater** [ycpatel813/trails-passport-auth#3]
Following your example project, I am unable to get this running.

```
error:
 TypeError: Cannot read property 'passport' of undefined
    at Object.module.exports.init.passport.connect.passport.serializeUser.passport.deserializeUser [as init] (/node_modules/trailpack-passport-auth/lib/passports.js:8:50)
    at MongoosepassportTrailpack.configure (/node_modules/trailpack-passport-auth/index.js:32:19)
    at /node_modules/trails/lib/trailpack.js:63:26
    at process._tickDomainCallback (node.js:412:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

Major differences between my project and your example is I'm using trailpack-mongoose 0.4.0 and trailpack-express 1.0.9 (as well as 0.0.10 of your lib).

**Comment by DarthHater** [comment]
I figured this out, it's because I didn't create a PassportService. Seems like your README could include that, as the trailpack seems to need it as a hard requirement, or you can use passport from within the trailpack and remove the need for an external service (not sure which you prefer).

**Comment by ycpatel813** [comment]
@DarthHater trailpack-passport is available at https://github.com/jaumard/trailpack-passport/.
That is improved version of passport if this full fill your requirement then check it because this repository is now used by me for a private project.

**Comment by DarthHater** [comment]
Unfortunately it will not work as it does not support Mongoose. Good to know though.
